changelog: The new release fixes #521748.
Frank Lichtenheld reported that collectd FTBFS because of the following
compiler error: 'const struct in6_addr' has no member named 'in6_u'. This had
already been fixed in 4.5.2.